site_name: Jay Khan
theme:
  name: material
  logo: assets/jk-logo-white.svg
  font:
    text: Lato

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

      primary: blue
      accent: green

copyright: Copyright &copy; 2022 Jay Khan

extra:
  homepage: https://jkhan.live
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaykhan_sound
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/jkhan.sound
    - icon: fontawesome/brands/github
      link: https://github.com/jaykhan-dev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jkhanprofile
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - tags:
      tags_file: tags.md
  - search

markdown_extensions:
  - meta
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home:
      - index.md
      - Resume: about/resume.md
      - Contact: about/contact.md

  - Work:
      - work/index.md

      - Web Design/Development:
          - Intro: work/uiux/intro.md
          - Appreci: work/uiux/appreci.md
          - Scribendi: work/uiux/scribendi.md
          - Budgetmore: work/uiux/budgetmore.md
          - Shaybeas: work/uiux/shaybeas.md
          - Pitbull Community: work/blockchain/pitbull-community.md

      - Graphic Design:
          - Intro: work/graphic-design/intro.md
          - Logos: work/graphic-design/logos.md
          - Posters: work/graphic-design/posters.md
          - Marketing: work/graphic-design/marketing.md
          - Social Media: work/graphic-design/social-media.md
          - Motion Graphics: work/graphic-design/motion-graphics.md

      - Design Philosophy: work/design-philosophy.md

      - Content Strategy: work/content-strategy.md

  - Tech Blog:
      - blog/index.md

      - JavaScript:
          - Vue JS:
              - Intro: blog/javascript/vue/vue-js.md
              - Axios CRUD: blog/javascript/vue/axios-crud.md
              - Nuxt ToDo: blog/javascript/vue/nuxt-todo.md
              - Trois JS: blog/javascript/vue/trois-js.md
              - Globals: blog/javascript/vue/globals.md
              - Tabs: blog/javascript/vue/creating-tabs.md
              - GSAP: blog/javascript/vue/gsap.md
              - Marquee: blog/javascript/vue/marquee.md
              - Pinia: blog/javascript/vue/pinia-algo.md
              - Responsive Nav: blog/javascript/vue/responsive-nav.md
              - Tab slots: blog/javascript/vue/creating-tabs.md
              - Tab pages: blog/javascript/vue/pages-tabs.md
              - Tailwind CSS: blog/javascript/vue/tailwind-css.md
              - Stacks setup: blog/javascript/vue/stacks-setup.md

          - React:
              - Intro: blog/javascript/react/intro.md
              - React Basics: blog/javascript/react-basics.md
              - React Hooks: blog/javascript/react-hooks.md

          - Express:
              - Express intro: blog/javascript/express/express-intro.md
              - Postgres CRUD: blog/javascript/express/postgres-crud.md
              - Bitcoin Lightning: blog/javascript/express/bitcoin-lightning.md
              - Deployment: blog/javascript/express/deployment.md

      - Python:
          - Intro to Python: blog/python/intro.md
          - Django:
              - Django intro: blog/python/django/django-intro.md
              - Heroku Deployment: blog/python/django/heroku-deployment.md
              - Ninja CRUD: blog/python/django/ninja-crud.md
              - Rest Framework CRUD: blog/python/django/rest-framework-crud.md
              - Wagtail intro: blog/python/django/wagtail-intro.md
          - General:
              - Hash Functions: blog/python/general/hash-functions.md

      - SQL:
          - Common:
              - Commands: blog/sql/common-commands.md
